/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AreaClassification: typeof import('./components/demo/echart/AreaClassification.vue')['default']
    ColorPicker: typeof import('./components/color/ColorPicker.vue')['default']
    Comment: typeof import('./components/comment/Comment.vue')['default']
    CommentTree: typeof import('./components/comment/CommentTree.vue')['default']
    Demo: typeof import('./components/demo/echart/demo.vue')['default']
    Demo1: typeof import('./components/demo/three/demo1.vue')['default']
    Demo10: typeof import('./components/demo/three/demo10/index.vue')['default']
    Demo2: typeof import('./components/demo/three/demo2.vue')['default']
    Demo3: typeof import('./components/demo/three/demo3.vue')['default']
    Demo4: typeof import('./components/demo/three/demo4.vue')['default']
    Demo5: typeof import('./components/demo/three/demo5.vue')['default']
    Demo6: typeof import('./components/demo/three/demo6.vue')['default']
    Demo7: typeof import('./components/demo/three/demo7.vue')['default']
    Demo8: typeof import('./components/demo/three/demo8.vue')['default']
    Demo9: typeof import('./components/demo/three/demo9/demo9.vue')['default']
    Echart: typeof import('./components/demo/echart.vue')['default']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Flex: typeof import('./components/demo/flex.vue')['default']
    HeaderBar: typeof import('./components/headerBar/HeaderBar.vue')['default']
    HeaderChannel: typeof import('./components/headerChannel/HeaderChannel.vue')['default']
    HeatMap: typeof import('./components/demo/echart/HeatMap.vue')['default']
    Introduced: typeof import('./components/demo/introduced.vue')['default']
    Jsx: typeof import('./components/demo/jsx.vue')['default']
    LoadingBuff: typeof import('./components/player/LoadingBuff.vue')['default']
    Login: typeof import('./components/login/Login.vue')['default']
    PlayerLoading: typeof import('./components/player/PlayerLoading.vue')['default']
    PlayerProgress: typeof import('./components/player/PlayerProgress.vue')['default']
    PlayerWrapper: typeof import('./components/player/PlayerWrapper.vue')['default']
    RelationTree: typeof import('./components/demo/echart/RelationTree.vue')['default']
    ReplyTextArea: typeof import('./components/comment/ReplyTextArea.vue')['default']
    RippleEffect: typeof import('./components/demo/echart/RippleEffect.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scence: typeof import('./components/demo/three/demo9/scence.vue')['default']
    Scene: typeof import('./components/demo/three/demo9/scene.vue')['default']
    SliderColumn: typeof import('./components/slider/SliderColumn.vue')['default']
    SliderRow: typeof import('./components/slider/SliderRow.vue')['default']
    Tsx: typeof import('./components/demo/tsx.vue')['default']
    Type: typeof import('./components/demo/type.vue')['default']
    Video: typeof import('./components/demo/video.vue')['default']
  }
}
